[Variables]
Bar_Opacity=a0
Bar_Opacity_Percent=63
Bar_Width =1920
Bar_Height =60
Bar_OffsetX =0
Bar_OffsetY =0

Section_Padding = 12

Color_Scheme1 =000000
Color_Scheme2 =FFFFFF
Color_Scheme3 =C9CC18
Color_Scheme4 =151515

Font_Face=Segoe UI
Font_Size=10
Font_Weight = 400

SubSkinPadding = 20
SubSkinCornerRadius = 10

SliderKnobRadius = 5
SliderHeight = 3

DefaultAddedModules=music,volume,weather,datetime,startmenu

